package ub.cse.algo;

import java.util.*;
import ub.cse.algo.util.Pair;

public class Solution {

    private Info info;
    private Graph graph;
    private ArrayList<Client> clients;
    private ArrayList<Integer> bandwidths;

    /**
     * Basic Constructor
     *
     * @param info: data parsed from input file
     */
    public Solution(Info info) {
        this.info = info;
        this.graph = info.graph;
        this.clients = info.clients;
        this.bandwidths = info.bandwidths;
    }

    /**
     * Method that returns the calculated 
     * SolutionObject as found by your algorithm
     *
     * @return SolutionObject containing the paths, priorities and bandwidths
     */

    private static class PairComparator implements Comparator<Pair<Integer,Integer>> {
        @Override
        public int compare(Pair<Integer,Integer> a, Pair<Integer,Integer> b){
            return -b.getFirst() - a.getFirst();
        }
    }

    public SolutionObject outputPaths() {
        SolutionObject sol = new SolutionObject();
        /* TODO: Your solution goes here */

        int[] distance = new int[graph.size()];
        int[] previous = new int[graph.size()];

        Arrays.fill(distance, Integer.MAX_VALUE);
        Arrays.fill(previous, -1);

        distance[graph.contentProvider] = 0;
        int maxBandwidth = Collections.max(bandwidths);

        PriorityQueue<Pair<Integer, Integer>> pq = new PriorityQueue<>(new PairComparator());
        PriorityQueue<Pair<Integer, Integer>> pq_sort = new PriorityQueue<>(new PairComparator());

        Set<Integer> visited = new HashSet<>();
        pq.offer(new Pair<>(0, graph.contentProvider));

        while (!pq.isEmpty()) {
            Pair<Integer, Integer> currentNode = pq.poll();
            if (visited.contains(currentNode.getSecond())) {
                continue;
            } else {
                visited.add(currentNode.getSecond());

                for (int neighbor : graph.get(currentNode.getSecond())) {
                    int weight;
                    if (neighbor < bandwidths.size()){
                        weight = maxBandwidth / bandwidths.get(neighbor);
                    }else{
                        weight = 1;
                    }

                    int newDistance = currentNode.getFirst() + weight;

                    if (newDistance < distance[neighbor] && neighbor < distance.length) {
                        distance[neighbor] = newDistance;
                        previous[neighbor] = currentNode.getSecond();
                        pq.offer(new Pair<>(newDistance, neighbor));
                    }
                }
            }
        }
        //-------------Sorting-------------//





        HashMap<Integer, ArrayList<Integer>> paths = new HashMap<>(clients.size());
        // For every client, traverse the prior array, creating the path
        for (Client client : clients) {
            ArrayList<Integer> path = new ArrayList<>();
            int currentNode = client.id;
            while (currentNode != -1) {
                path.add(0, currentNode);
                currentNode = previous[currentNode];
            }
            paths.put(client.id, path);
        }
        sol.paths = paths;

        //keeps track of packet traffic and router loads
        int[] load = new int[bandwidths.size()];
        //get the path for each client
        for (Client client : clients) {
            ArrayList<Integer> path = paths.get(client.id);
            for (int node : path) {
                if (node < bandwidths.size()) {
                    //each time we reach a node in the path we keep track of the node and the amount of times it visited
                    load[node]++;
                }
            }
        }

        //new bandwidths list to keep track of the bandwidths
        ArrayList<Integer> tempBandwidths = new ArrayList<>(bandwidths);
        //if our original bandwidth is lower than the load we just set it to the load
        for (int node = 0; node < bandwidths.size(); node++) {
            int required = load[node];
            int original = bandwidths.get(node);
            if (required > original) {
                tempBandwidths.set(node, required);
            }
        }
        sol.bandwidths = tempBandwidths;
        //sort deleted since it does absolutely nothing


        return sol;
    }
}

// 1.Implement Dijkstra to generate our paths, weight can either be our bandwidths or load/bandwidth
        /*2.then calculate how many times each node passes through another node, this will give our load vs bandwidth
        3.We will then determine if we should increase the bandwidth using the formula, updated - current
            if greater than 0
                upgrade
            else
                leave alone
         4.Then sort the order of our paths generated by Dijkstra by tolerance or payment which ever proves more effective
         */
