package ub.cse.algo;

import java.util.*;
import ub.cse.algo.util.Pair;

public class Solution {

    private Info info;
    private Graph graph;
    private ArrayList<Client> clients;
    private ArrayList<Integer> bandwidths;

    /**
     * Basic Constructor
     *
     * @param info: data parsed from input file
     */
    public Solution(Info info) {
        this.info = info;
        this.graph = info.graph;
        this.clients = info.clients;
        this.bandwidths = info.bandwidths;
    }

    /**
     * Method that returns the calculated 
     * SolutionObject as found by your algorithm
     *
     * @return SolutionObject containing the paths, priorities and bandwidths
     */

    private static class PairComparator implements Comparator<Pair<Integer,Integer>> {
        @Override
        public int compare(Pair<Integer,Integer> a, Pair<Integer,Integer> b){
            return -b.getFirst() - a.getFirst();
        }
    }

    public SolutionObject outputPaths() {
        SolutionObject sol = new SolutionObject();
        /* TODO: Your solution goes here */


        //-------------DIJKSTRA-------------//
        int[] distance = new int[graph.size()];
        int[] previous = new int[graph.size()];

        Arrays.fill(distance, Integer.MAX_VALUE);
        Arrays.fill(previous, -1);

        distance[graph.contentProvider] = 0;

        PriorityQueue<Pair<Integer, Integer>> pq = new PriorityQueue<>(new PairComparator());
        PriorityQueue<Pair<Integer, Integer>> pq_sort = new PriorityQueue<>(new PairComparator());

        Set<Integer> visited = new HashSet<>();
        pq.offer(new Pair<>(0, graph.contentProvider));

        while (!pq.isEmpty()) {
            Pair<Integer, Integer> currentNode = pq.poll();
            if (visited.contains(currentNode.getSecond())) {
                continue;
            } else {
                visited.add(currentNode.getSecond());

                for (int neighbor : graph.get(currentNode.getSecond())) {
                    int newDistance = currentNode.getFirst() + bandwidths.get(neighbor);

                    if (newDistance < distance[neighbor]) {
                        distance[neighbor] = newDistance;
                        previous[neighbor] = currentNode.getSecond();
                        pq.offer(new Pair<>(newDistance, neighbor));
                    }
                }
            }
        }
        //-------------Sorting-------------//





        //-------------Paths-Generation-------------//
        HashMap<Integer, ArrayList<Integer>> paths = new HashMap<>(clients.size());
        // For every client, traverse the prior array, creating the path
        for (Client client : clients) {
            ArrayList<Integer> path = new ArrayList<>();
            int currentNode = client.id;
            while (currentNode != -1) {
                /*
                    Add this ID to the beginning of the
                    path so the path ends with the client
                 */
                path.add(0, currentNode);
                currentNode = previous[currentNode];
            }
            paths.put(client.id, path);
        }
        sol.paths = paths;
        //-------------Bandwidth-------------//

        HashMap<Client,Integer> hashMap = new HashMap<>();

        for(int i = 0; i < graph.size(); i++){
            for(int j = 0; j < clients.size(); j++){
                if(graph.get(i).contains(j)){
                    if(!hashMap.containsKey(clients.get(j))){
                        hashMap.put(clients.get(j),1);
                    } else {
                        Integer val = hashMap.get(clients.get(j));
                        val += 1;
                        hashMap.put(clients.get(j),val);
                    }
                }
                if(hashMap.get(clients.get(j)) != null){
                    if(hashMap.get(clients.get(j)) > bandwidths.get(clients.get(j).id)){
                        int val = Math.max(0,(bandwidths.get(clients.get(j).id) + 1) - (bandwidths.get(clients.get(j).id)) );

                        if(val > 0){
                            int oldBandwidth = (bandwidths.get(clients.get(j).id) );
                            bandwidths.set(clients.get(j).id,oldBandwidth + 1);
                        }
                    }
                }
            }
        }
        sol.bandwidths = bandwidths;

        return sol;
    }
}

// 1.Implement Dijkstra to generate our paths, weight can either be our bandwidths or load/bandwidth
        /*2.then calculate how many times each node passes through another node, this will give our load vs bandwidth
        3.We will then determine if we should increase the bandwidth using the formula, updated - current
            if greater than 0
                upgrade
            else
                leave alone
         4.Then sort the order of our paths generated by Dijkstra by tolerance or payment which ever proves more effective
         */
